# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=12)),
                ('bar_code', models.CharField(blank=True, max_length=64)),
                ('product_date', models.DateTimeField(auto_now_add=True)),
                ('last_use_date', models.DateTimeField(auto_now_add=True)),
                ('first_use_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SerialData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('addr', models.CharField(blank=True, max_length=12, null=True)),
                ('cs', models.CharField(blank=True, max_length=10, null=True)),
                ('data_len', models.CharField(blank=True, max_length=10, null=True)),
                ('status_word', models.CharField(blank=True, max_length=10, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip4_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('com_id', models.CharField(blank=True, max_length=5)),
                ('user_id', models.CharField(max_length=30, null=True)),
                ('user_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bug_manage.SerialData')),
                ('user_meter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bug_manage.Meter')),
            ],
        ),
    ]
