# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logic',
            old_name='frame',
            new_name='frame_set',
        ),
        migrations.AddField(
            model_name='funcmessage',
            name='frame_set',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
