# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_manage', '0003_auto_20171107_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='send_data',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='send_status',
            field=models.BooleanField(default=False),
        ),
    ]
