# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_manage', '0003_auto_20171205_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logic',
            old_name='func_id',
            new_name='func',
        ),
    ]
