# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_manage', '0005_auto_20171107_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('founder', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BugFrameRecvLogic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_index', models.IntegerField(blank=True, default=0)),
                ('end_idnex', models.IntegerField(blank=True, default=0)),
                ('change_data', models.CharField(blank=True, max_length=200, null=True)),
                ('logic', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BugFrameSendLogic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_index', models.IntegerField(blank=True, default=0)),
                ('end_idnex', models.IntegerField(blank=True, default=0)),
                ('change_data', models.CharField(blank=True, max_length=200, null=True)),
                ('logic', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BugLogic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_delay_time', models.IntegerField(blank=True, default=0)),
                ('begin_delay_time', models.IntegerField(blank=True, default=0)),
                ('is_read_addr', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('is_recv_data', models.BooleanField(default=True)),
                ('read_data', models.CharField(blank=True, max_length=200, null=True)),
                ('is_change_send_frame', models.BooleanField(default=False)),
                ('is_change_recv_frame', models.BooleanField(default=False)),
                ('logic', models.CharField(max_length=200)),
                ('changed_recv_frame_logic', models.ManyToManyField(blank=True, to='bug_manage.BugFrameRecvLogic')),
                ('changed_send_frame_logic', models.ManyToManyField(blank=True, null=True, to='bug_manage.BugFrameSendLogic')),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='step',
            field=models.ManyToManyField(blank=True, null=True, to='bug_manage.BugLogic'),
        ),
    ]
