# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_manage', '0006_auto_20171114_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='step',
            field=models.ManyToManyField(blank=True, to='bug_manage.BugLogic'),
        ),
        migrations.AlterField(
            model_name='buglogic',
            name='changed_send_frame_logic',
            field=models.ManyToManyField(blank=True, to='bug_manage.BugFrameSendLogic'),
        ),
    ]
