# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_manage', '0007_auto_20171114_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buglogic',
            name='changed_recv_frame_logic',
        ),
        migrations.RemoveField(
            model_name='buglogic',
            name='changed_send_frame_logic',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='step',
        ),
        migrations.AddField(
            model_name='bug',
            name='step',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='BugFrameRecvLogic',
        ),
        migrations.DeleteModel(
            name='BugFrameSendLogic',
        ),
        migrations.DeleteModel(
            name='BugLogic',
        ),
    ]
