# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_manage', '0008_auto_20171121_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='step',
            field=models.FileField(blank=True, max_length=5000, null=True, upload_to=''),
        ),
    ]
