# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_manage', '0009_auto_20171121_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=12)),
                ('ischange_addr', models.BooleanField(default=False)),
                ('issend_delay', models.BooleanField(default=False)),
                ('isrecv_delay', models.BooleanField(default=False)),
                ('isFE_begin', models.BooleanField(default=False)),
                ('send_delay', models.IntegerField(blank=True, null=True)),
                ('read_delay', models.IntegerField(blank=True, null=True)),
                ('step_num', models.IntegerField(blank=True, null=True)),
                ('frame', models.CharField(blank=True, max_length=500, null=True)),
                ('func_id', models.CharField(blank=True, max_length=100, null=True)),
                ('val0', models.CharField(blank=True, max_length=100, null=True)),
                ('val1', models.CharField(blank=True, max_length=100, null=True)),
                ('val2', models.CharField(blank=True, max_length=100, null=True)),
                ('val3', models.CharField(blank=True, max_length=100, null=True)),
                ('val4', models.CharField(blank=True, max_length=100, null=True)),
                ('val5', models.CharField(blank=True, max_length=100, null=True)),
                ('val6', models.CharField(blank=True, max_length=100, null=True)),
                ('val7', models.CharField(blank=True, max_length=100, null=True)),
                ('val8', models.CharField(blank=True, max_length=100, null=True)),
                ('val9', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bug',
            name='step',
        ),
        migrations.AddField(
            model_name='bug',
            name='step',
            field=models.ManyToManyField(to='bug_manage.Logic'),
        ),
    ]
