# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_manage', '0011_auto_20171128_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logic',
            name='isrecv_delay',
        ),
        migrations.RemoveField(
            model_name='logic',
            name='issend_delay',
        ),
        migrations.AddField(
            model_name='logic',
            name='display_msg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
