# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_manage', '0012_auto_20171129_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='step',
            field=models.ManyToManyField(related_name='step', to='bug_manage.Logic'),
        ),
    ]
