# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_manage', '0013_auto_20171129_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncMessage',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=200)),
            ],
        ),
    ]
