# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_manage', '0014_funcmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcmessage',
            name='func_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
