# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug_manage', '0015_funcmessage_func_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='logic',
            name='step_num',
        ),
        migrations.AlterField(
            model_name='task',
            name='step',
            field=models.ManyToManyField(related_name='step', to='bug_manage.StepAction'),
        ),
        migrations.AddField(
            model_name='stepaction',
            name='act',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bug_manage.Logic'),
        ),
    ]
