# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_manage', '0016_auto_20171129_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='msg',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='funcmessage',
            name='msg',
            field=models.CharField(max_length=500),
        ),
    ]
