# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_management_coding', models.CharField(max_length=30)),
                ('worker_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('product_status', models.CharField(max_length=30)),
                ('product_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
