# Generated by Django 2.0 on 2017-12-28 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip4_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('com_id', models.CharField(blank=True, max_length=5)),
                ('user_id', models.CharField(max_length=30, null=True)),
                ('send_status', models.BooleanField(default=False)),
                ('get_status', models.BooleanField(default=False)),
                ('get_data', models.CharField(blank=True, max_length=200, null=True)),
                ('send_data', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuncMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('func_id', models.CharField(blank=True, max_length=200, null=True)),
                ('frame_set', models.CharField(blank=True, max_length=500, null=True)),
                ('msg', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Logic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=12)),
                ('ischange_addr', models.BooleanField(default=False)),
                ('isFE_begin', models.BooleanField(default=False)),
                ('send_delay', models.IntegerField(blank=True, null=True)),
                ('read_delay', models.IntegerField(blank=True, null=True)),
                ('display_msg', models.CharField(blank=True, max_length=200, null=True)),
                ('val0', models.CharField(blank=True, max_length=100, null=True)),
                ('val1', models.CharField(blank=True, max_length=100, null=True)),
                ('val2', models.CharField(blank=True, max_length=100, null=True)),
                ('val3', models.CharField(blank=True, max_length=100, null=True)),
                ('val4', models.CharField(blank=True, max_length=100, null=True)),
                ('val5', models.CharField(blank=True, max_length=100, null=True)),
                ('val6', models.CharField(blank=True, max_length=100, null=True)),
                ('val7', models.CharField(blank=True, max_length=100, null=True)),
                ('val8', models.CharField(blank=True, max_length=100, null=True)),
                ('val9', models.CharField(blank=True, max_length=100, null=True)),
                ('func', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bug_manage.FuncMessage')),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=12)),
                ('bar_code', models.CharField(blank=True, max_length=64)),
                ('product_date', models.DateTimeField(auto_now_add=True)),
                ('last_use_date', models.DateTimeField(auto_now_add=True)),
                ('first_use_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SerialData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('addr', models.CharField(blank=True, max_length=12, null=True)),
                ('status_word', models.CharField(blank=True, max_length=10, null=True)),
                ('data_len', models.CharField(blank=True, max_length=10, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('cs', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StepAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('act', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bug_manage.Logic')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('founder', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('msg', models.CharField(blank=True, max_length=500, null=True)),
                ('step', models.ManyToManyField(related_name='step', to='bug_manage.StepAction')),
            ],
        ),
        migrations.AddField(
            model_name='clientuser',
            name='user_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bug_manage.SerialData'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='user_meter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bug_manage.Meter'),
        ),
    ]
